version: 2

sphinx:
  configuration: scripts/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - emacs
  jobs:
    pre_create_environment:
      - echo "### 'pre_create_environment' step"
      - emacs --version
    post_build:
      - echo "### 'post_build' step"
      - rm -rf _readthedocs
      - emacs --script scripts/publish-to-rtd.el
      - find
